#supabase_url = "https://lalalala.supabase.co"
supabase_url = 'https://ktexmliefragugupzmqw.supabase.co'
#supabase_service_key = "lalalala"
supabase_service_key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZXhtbGllZnJhZ3VndXB6bXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODUyNjg1MjcsImV4cCI6MjAwMDg0NDUyN30.7DBDCcqelS0GNojPqv0zuvCT5vs5x2Codxyr5cDPZvU'
openai_api_key_head = 'sk-9utMl6JfUfgm4lRIXmK'
openai_api_key_tail = 'bT3BlbkFJBvNXhwDz9WJrzmi5G6FP'
anthropic_api_key = ""
self_hosted = "true"
usage_limit = 1000